### ISSUE TITLE
Quiet Dialogue

### ISSUE THREAD

**Issue by sethreign8103** [TheOfficialFloW/crazytaxi_vita#3]
At any point in the game all of the dialogue and possibly sound effects is extremely quiet while the music is at a normal level.

**Comment by redesigndev** [comment]
I believe it's the other way around - the music is way too loud, while the sound effects appear to be at a normal level. Sometimes, the music seems to fix itself (pausing, suspending to LiveArea, other times seemingly randomly) but it's only temporary, the volume shoots back up after a short while.

**Comment by Rinnegatamante** [comment]
This has been fixed locally, will be available on next release.

**Comment by sethreign8103** [comment]
> I believe it's the other way around - the music is way too loud, while the sound effects appear to be at a normal level. Sometimes, the music seems to fix itself (pausing, suspending to LiveArea, other times seemingly randomly) but it's only temporary, the volume shoots back up after a short while.

Either way the music drowns out any of the dialogue and the issue is still present in the latest version. I've played several hour long sessions and the volume never fixed itself for me.
